[package]
name = "rust-libavif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "src/build.rs"

[dependencies]
byteorder = "1.5.0"
exitcode = "1.1.2"
derivative = "2.2.0"
# TODO: this is needed for capi only.
libc = "0.2"
# TODO: make this test only.
test-case = "*"
# TODO: make this test only.
seq-macro = "*"

[features]
capi = []

[package.metadata.capi.header]
name = "avif"
subdirectory = "avif"