[package]
name = "rust-libavif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "src/build.rs"

[dependencies]
byteorder = "1.5.0"
# TODO: this is only needed for binary crates.
exitcode = "1.1.2"
derivative = "2.2.0"

[dev-dependencies]
test-case = "3.3.1"
seq-macro = "0.3.5"
tempfile = "3.8.1"

[features]
default = ["dav1d"]
capi = []
dav1d = []
libgav1 = []

[package.metadata.capi.header]
name = "avif"
subdirectory = "avif"