language = "C"
include_guard = "AVIF_H"
tab_width = 4
style = "both"
cpp_compat = true
usize_is_size_t = true

[export.rename]
"ChromaSamplePosition" = "avifChromaSamplePosition"
"ColorPrimaries" = "avifColorPrimaries"
"MatrixCoefficients" = "avifMatrixCoefficients"
"Source" = "avifDecoderSource"
"TransferCharacteristics" = "avifTransferCharacteristics"

[enum]
rename_variants = "QualifiedScreamingSnakeCase"