language = "C"
include_guard = "AVIF_H"
tab_width = 4
style = "both"
cpp_compat = true
usize_is_size_t = true

[export.rename]
"ChromaSamplePosition" = "avifChromaSamplePosition"
"ColorPrimaries" = "avifColorPrimaries"
"MatrixCoefficients" = "avifMatrixCoefficients"
"ProgressiveState" = "avifProgressiveState"
"Source" = "avifDecoderSource"
"TransferCharacteristics" = "avifTransferCharacteristics"
"DEFAULT_IMAGE_COUNT_LIMIT" = "AVIF_DEFAULT_IMAGE_COUNT_LIMIT"
"DEFAULT_IMAGE_DIMENSION_LIMIT" = "AVIF_DEFAULT_IMAGE_DIMENSION_LIMIT"
"DEFAULT_IMAGE_SIZE_LIMIT" = "AVIF_DEFAULT_IMAGE_SIZE_LIMIT"

[enum]
rename_variants = "QualifiedScreamingSnakeCase"
